# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# url variables
# library's domain
url: https://www.lib.uidaho.edu
# location on the website
baseurl: /digital
description: University of Idaho Digital Collections

# url to the shared assets folder on Digital
digital-assets: https://www.lib.uidaho.edu/assets

# main url, used to point at server even when on dev server
liburl: https://www.lib.uidaho.edu


# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]
